server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/blank?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: blankuser
    password: blankpasswd

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true